### ISSUE TITLE
Colors for kitty terminal

### ISSUE THREAD

**Issue by kristijanhusak** [nightsense/cosmic_latte#1]
Hi,

great color scheme, especially the light version, i really like it.

Is there a chance to add a [Kitty terminal](https://sw.kovidgoyal.net/kitty) colors?

Here's link to color scheme docs https://sw.kovidgoyal.net/kitty/conf.html#color-scheme.

It shouldn't be hard. I wanted to do it, but you know better how to connect the right colors.

**Comment by nightsense** [comment]
Glad you like it! I gave the Kitty theme a try, let me know if you feel anything should be tweaked.

**Comment by kristijanhusak** [comment]
Looks great, thanks!
