### ISSUE TITLE
Neovim terminal colors

### ISSUE THREAD

**Issue by kristijanhusak** [nightsense/cosmic_latte#2]
Hi,

I noticed that neovim terminal colors (g:terminal_color_$NUM) are a bit different then colors in the regular terminal (at least kitty that you recently added). Here's how g:terminal_color_8 looks in neovim terminal:

![neovim-terminal](https://i.imgur.com/xn4Fy9p.png)

And here how it looks in kitty:
![kitty-terminal](https://i.imgur.com/zQIPSpM.png)

I'm not sure for other terminals. I think the kitty version is much more visible and readable then current neovim terminal color. Can that be tweaked?

**Comment by nightsense** [comment]
Fixed, as noted at #3.
