### ISSUE TITLE
How to rebuild from source?

### ISSUE THREAD

**Issue by eddyg** [nightsense/cosmic_latte#6]
Greetings!

Thanks for some great themes!

I'd like to try making some adjustments to some of the colors. To that end, I've cloned your (old) fork of `colortemplate`, but there are differences with the files that are generated compared to what's in the repo.

For example, in `cosmic_latte_light.sh`, I end up with lines like:

    color08="#efe4d2" # Base 03 - Bright Black
      put_template_custom Pi #485a62 # bold color

but those same lines in the repo look like this:

    color08="ef/e4/d2" # Base 03 - Bright Black
      put_template_custom Pi 485a62 # bold color

Do you do some kind of manual post-processing, or am I just missing something obvious?

Thanks again.

**Comment by nightsense** [comment]
Hi @eddyg, glad you like em!

The command you need is `fish generate.fish` (to be run in the `templates` directory). I now realize this should really be stated in the readme, so I've added it.
